### ISSUE TITLE
Too stupid to run nix run

### ISSUE THREAD

**Issue by shyim** [Xe/gohello#1]
Hey,

I am trying to get into Nix flakes and read your awesome blog post https://christine.website/blog/nix-flakes-1-2022-02-21. 

I am now hanging on the `nix run` command. It fails always with `error: attribute 'defaultApp.x86_64-linux' should have type 'derivation'`

That happens also with this repository:

```
nix run github:Xe/gohello/main
error: attribute 'defaultApp.x86_64-linux' should have type 'derivation'
```

Is this guide maybe outdated? My system is

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.3, Ubuntu, 22.04 (Jammy Jellyfish), nobuild`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.8.0`
 - channels(dev): `"nixpkgs"`
 - nixpkgs: `/home/dev/.nix-defexpr/channels/nixpkgs`
 ```

**Comment by Xe** [comment]
Try again?

**Comment by shyim** [comment]
Works thanks :)
